FROM centos:7
RUN sed -i '/^mirrorlist/d' /etc/yum.repos.d/*.repo \
    && sed -i 's/^# *baseurl/baseurl/' /etc/yum.repos.d/*.repo \
    && sed -i 's/mirror.centos.org/vault.centos.org/' /etc/yum.repos.d/*.repo \
    && yum install -y epel-release centos-release-scl \
    && sed -i '/^mirrorlist/d' /etc/yum.repos.d/*.repo \
    && sed -i 's/^# *baseurl/baseurl/' /etc/yum.repos.d/*.repo \
    && sed -i 's/mirror.centos.org/vault.centos.org/' /etc/yum.repos.d/*.repo \
    && yum update -y \
    && yum install -y git make \
    devtoolset-9-toolchain devtoolset-9-libasan-devel \
    pkg-config wget python36-devel valgrind \
    jq tcpreplay iproute sudo zlib-devel \
    openssl-devel rpm-build readline-devel \
    && alternatives --install /usr/bin/gcc gcc /opt/rh/devtoolset-9/root/usr/bin/gcc 60 \
    && alternatives --install /usr/bin/g++ g++ /opt/rh/devtoolset-9/root/usr/bin/g++ 60 \
    && alternatives --install /usr/bin/cc cc /opt/rh/devtoolset-9/root/usr/bin/gcc 60 \
    && yum clean all \
    && rm -rf /var/cache/yum

RUN wget -c https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.1.tar.gz -O - | tar xzvf -
RUN cd /ruby-2.7.1 && ./configure && make && make install && cd / && rm -rf /ruby-2.7.1
RUN pip3 install --upgrade pip && pip3 install setuptools wheel && pip3 install jsonschema cryptography Cython
RUN gem install dotenv -v 2.8.1 \
    && gem install --no-document fpm
