FROM debian:9
RUN sed -i 's/[[:alpha:]]\+\.debian\.org/archive.debian.org/g' /etc/apt/sources.list \
    && sed -i '/stretch-updates/d' /etc/apt/sources.list \
    && apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y git pkg-config wget python3-dev python3-pip jq \
    tcpreplay iproute2 sudo debconf zlib1g-dev libssl-dev \
    valgrind libc-dev libffi-dev make dpkg-dev gcc g++ --no-install-recommends \
    && apt-get -f install \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip && pip3 install setuptools wheel \
    && pip3 install jsonschema cryptography Cython
