FROM ubuntu:16.04
RUN apt-get update \
    && apt-get install -y software-properties-common \
    git make dpkg-dev libc-dev \
    pkg-config wget python3-dev python3-pip \
    valgrind jq tcpreplay iproute2 sudo \
    libffi-dev build-essential \
    zlib1g-dev libssl-dev --no-install-recommends \
    && add-apt-repository ppa:ubuntu-toolchain-r/test \
    && apt-get update \
    && apt-get install -y gcc-9 g++-9 --no-install-recommends \
    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 60 \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 \
    && update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-9 60 \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade 'pip==20.3.4' && pip3 install setuptools wheel && pip3 install jsonschema cryptography Cython
