FROM centos:8
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
RUN yum install -y epel-release \
    && yum update -y \
    && yum install -y git make \
    gcc-toolset-9-gcc gcc-toolset-9-gcc-c++ gcc-toolset-9-libasan-devel \
    pkg-config wget python36-devel valgrind \
    jq tcpreplay iproute sudo zlib-devel \
    openssl-devel \
    && yum update -y \
    && alternatives --install /usr/bin/gcc gcc /opt/rh/gcc-toolset-9/root/usr/bin/gcc 60 \
    && alternatives --install /usr/bin/g++ g++ /opt/rh/gcc-toolset-9/root/usr/bin/g++ 60 \
    && alternatives --install /usr/bin/cc cc /opt/rh/gcc-toolset-9/root/usr/bin/gcc 60 \
    && yum clean all \
    && rm -rf /var/cache/yum

RUN pip3 install --upgrade pip && pip3 install setuptools wheel && pip3 install jsonschema cryptography Cython
