FROM etta/ubuntu:18.04
RUN apt-get update \
    && apt-get install -y software-properties-common unzip --no-install-recommends \
    && apt-add-repository --yes --update ppa:ansible/ansible \
    && apt-get -y install ansible --no-install-recommends \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://releases.hashicorp.com/packer/1.6.6/packer_1.6.6_linux_amd64.zip -O /tmp/packer.zip \
    && unzip /tmp/packer.zip -d /tmp \
    && cp /tmp/packer /usr/bin/

RUN adduser --disabled-password --gecos '' packer
RUN adduser packer sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER packer
WORKDIR /home/packer
