FROM almalinux:10
RUN dnf install -y epel-release \
    && dnf update -y \
    && dnf group install -y --with-optional "Development Tools" \
    && dnf install -y openssl-devel valgrind \
    && dnf install -y libasan libtsan libubsan liblsan \
    && dnf install -y python3 python3-devel python3-pip \
    && dnf install -y wget jq iproute sudo \
    && dnf clean all \
    && rm -rf /var/cache/dnf \
    && python3 -m venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"
RUN pip3 install --upgrade pip \
    && pip3 install setuptools wheel \
    && pip3 install jsonschema cryptography Cython

RUN dnf install -y ruby rpm-build squashfs-tools \
    && gem install fpm
