# Stock AlmaLinux 8 toolchain: "Development Tools" provides gcc 8.5, python 3.12
FROM almalinux:8
RUN dnf install -y epel-release \
    && dnf update -y \
    && dnf group install -y --with-optional "Development Tools" \
    && dnf install -y openssl-devel gmp-devel zlib-devel \
    && dnf install -y libasan libtsan libubsan liblsan \
    && dnf install -y python3.12-devel \
    && dnf install -y valgrind wget jq tcpreplay iproute sudo lcov \
    && dnf clean all \
    && rm -rf /var/cache/dnf \
    && python3 -m venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"
RUN pip install --upgrade pip \
    && pip install --upgrade setuptools wheel \
    && pip install --upgrade jsonschema cryptography Cython

# Disabled: no RHEL8 rpm use case (saves 1hr build time)
#
# Default ruby on AlmaLinux 8 is too outdated to execute "gem install fpm"
# RUN dnf install -y rbenv rpm-build squashfs-tools \
#     && eval "$(rbenv init -)" \
#     && echo 'eval "$(rbenv init -)"' >> .bashrc \
#     && rbenv install "$(rbenv install -l | grep -v - | tail -1)" \
#     && rbenv global "$(rbenv install -l | grep -v - | tail -1)" \
#     && gem install fpm \
#     && chmod o+x /root
# ENV PATH="/root/.rbenv/shims:$PATH"
