FROM ubuntu:18.04
RUN apt-get update \
    && apt-get install -y software-properties-common \
    git make dpkg-dev libc-dev \
    pkg-config wget python3-dev python3-pip \
    valgrind jq tcpreplay iproute2 sudo \
    snapd curl unzip \
    zlib1g-dev libssl-dev ruby-dev rubygems --no-install-recommends \
    && add-apt-repository ppa:ubuntu-toolchain-r/test \
    && apt-get update \
    && apt-get install -y gcc-9 g++-9 --no-install-recommends \
    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 60 \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 \
    && update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-9 60 \
    && rm -rf /var/lib/apt/lists/* \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install

RUN pip3 install --upgrade pip && pip3 install setuptools wheel && pip3 install jsonschema cryptography Cython
RUN gem install public_suffix -v 4.0.7 \
    && gem install dotenv -v 2.8.1 \
    && gem install --no-ri --no-rdoc fpm
