FROM ubuntu:20.04
RUN apt-get update \
    && apt-get install -y git build-essential \
    pkg-config wget python3-dev python3-pip \
    valgrind jq tcpreplay iproute2 sudo \
    zlib1g-dev libssl-dev ruby-dev rubygems --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip && pip3 install setuptools wheel && pip3 install jsonschema cryptography Cython
RUN gem install dotenv -v 2.8.1 && gem install fpm
