# Stock AlmaLinux 10 toolchain: "Development Tools" provides gcc 14.3, python 3.12
FROM almalinux:10
RUN dnf install -y epel-release \
    && dnf update -y \
    && dnf group install -y --with-optional "Development Tools" \
    && dnf install -y openssl-devel gmp-devel zlib-devel xsimd-devel \
    && dnf install -y libasan libtsan libubsan liblsan \
    && dnf install -y python3-devel \
    && dnf install -y valgrind wget jq tcpreplay iproute sudo lcov \
    && dnf clean all \
    && rm -rf /var/cache/dnf \
    && python3 -m venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"
RUN pip install --upgrade pip \
    && pip install --upgrade setuptools wheel \
    && pip install --upgrade jsonschema cryptography Cython

RUN dnf install -y ruby rpm-build squashfs-tools \
    && gem install fpm
