FROM alpine:latest
RUN apk update && \
    apk add --no-cache git make gcc g++ linux-headers pkgconfig \
    python3 python3-dev py3-pip \
    valgrind jq tar zlib-dev openssl-dev \
    libffi-dev ruby ruby-dev ruby-bundler \
    && python -m venv /opt/venv \
    && rm -rf /var/cache/apk/* \
    && rm -rf /root/.cache/*

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/edge/community/" >> /etc/apk/repositories && \
    apk update && \
    apk add --no-cache tcpreplay \
    && rm -rf /var/cache/apk/* \
    && rm -rf /root/.cache/*

ENV PYTHONUNBUFFERED=1
ENV PATH="/opt/venv/bin:$PATH"
RUN pip3 install --no-cache --upgrade pip && pip3 install setuptools wheel && pip3 install jsonschema cryptography Cython
RUN gem install fpm
