FROM ubuntu:22.04
RUN apt-get update \
    && apt-get install -y git build-essential \
    pkg-config wget python3-dev python3-pip \
    valgrind jq tcpreplay iproute2 sudo \
    snapd curl unzip \
    zlib1g-dev libssl-dev ruby-dev rubygems --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install

RUN pip3 install --upgrade pip && pip3 install setuptools wheel && pip3 install jsonschema cryptography Cython
RUN gem install fpm
