-- OIDs assigned to Netscape
--
-- Source: https://www.alvestrand.no/objectid/2.16.840.1.113730.1.4.html
-- Retrieved: Jan 31 2020


NetscapeCertificateExtension OBJECT IDENTIFIER ::= { 2 16 840 1 113730 1 }

-- Object identifiers with this prefix identify Netscape extensions
-- within X.509 version 3 certificates.


RevocationURL OBJECT IDENTIFIER ::= { 2 16 840 1 113730 1 3 }

-- The value is an IA5String. It is a relative or absolute URL that
-- can be used to check the revocation status of a certificate. The
-- revocation check will be performed as an HTTP GET method using a
-- url that is the concatenation of revocation-url and
-- certificate-serial-number. Where the certificate-serial-number is
-- encoded as a string of ascii hexadecimal digits. For example, if
-- the netscape-base-url is https://www.certs-r-us.com/, the
-- netscape-revocation-url is cgi-bin/check-rev.cgi?, and the
-- certificate serial number is 173420, the resulting URL would be:
-- https://www.certs-r-us.com/cgi-bin/check-rev.cgi?02a56c


CaRevocationURL OBJECT IDENTIFIER ::= { 2 16 840 1 113730 1 4 }

-- The value is an IA5String. It is a relative or absolute URL that
-- can be used to check the revocation status of any certificates that
-- are signed by the CA that this certificate belongs to. This
-- extension is only valid in CA certificates. The use of this
-- extension is the same as the netscape-revocation-url extension.


SSLServerName OBJECT IDENTIFIER ::= {  2 16 840 1 113730 1 12 }

-- The value is an IA5String. It is a "shell expression" that can be
-- used to match the hostname of the SSL server that is using this
-- certificate. It is recommended that if the server's hostname does
-- not match this pattern the user be notified and given the option to
-- terminate the SSL connection. If this extension is not present then
-- the CommonName in the certificate subject's distinguished name is
-- used for the same purpose.


NetscapeCertificateComment OBJECT IDENTIFIER ::= { 2 16 840 1 113730 1 13 }

-- An X.509 v3 certificate extension used to include free-form text
-- comments inside certificates.
