char license_string[] =
    "Copyright (c) 2019-2020 Cisco Systems, Inc.\n"
    "All rights reserved.\n"
    "\n"
    "  Redistribution and use in source and binary forms, with or without\n"
    "  modification, are permitted provided that the following conditions\n"
    "  are met:\n"
    "\n"
    "    Redistributions of source code must retain the above copyright\n"
    "    notice, this list of conditions and the following disclaimer.\n"
    "\n"
    "    Redistributions in binary form must reproduce the above\n"
    "    copyright notice, this list of conditions and the following\n"
    "    disclaimer in the documentation and/or other materials provided\n"
    "    with the distribution.\n"
    "\n"
    "    Neither the name of the Cisco Systems, Inc. nor the names of its\n"
    "    contributors may be used to endorse or promote products derived\n"
    "    from this software without specific prior written permission.\n"
    "\n"
    "  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
    "  \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
    "  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\n"
    "  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE\n"
    "  COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,\n"
    "  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\n"
    "  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR\n"
    "  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\n"
    "  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,\n"
    "  STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\n"
    "  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED\n"
    "  OF THE POSSIBILITY OF SUCH DAMAGE.\n"
    "\n"
    "For current and comprehensive license information, please see:\n"
    "\n"
    " * https://github.com/cisco/mercury/LICENSE for the main license\n"
    " * https://github.com/cisco/mercury/src/lctrie for the lctrie license;\n"
    "   this package is copyright 2016-2017 Charles Stewart\n"
    "   <chuckination_at_gmail_dot_com>\n"
    " * https://github.com/cisco/mercury/src/rapidjson for the rapidjson license;\n"
    "   this package is copyright 2015 THL A29 Limited, a Tencent company, and\n"
    "   Milo Yip.";
