// krb5_params.hpp
//
// this file was autogenerated at 2025-06-10T14:27:53Z
// you should edit the source file(s) instead of this one
//
// source files:
//     kerberos-parameters-1.csv
//     kerberos-parameters-2.csv
//     pre-authentication.csv
//

#ifndef KRB5_PARAMS_HPP
#define KRB5_PARAMS_HPP

template <typename T>
class encryption_type : public encoded<T> {
    static_assert(std::is_unsigned_v<T>, "T must be an unsigned integer");
public:
    void write_json(json_object &o) const {
        const char *name = get_name();
        if (name == nullptr) {
            o.print_key_unknown_code("encryption_type", encoded<T>::value());
        } else {
            o.print_key_string("encryption_type", name);
        }
    }
    enum code {
        reserved                     = 0,
        des_cbc_crc                  = 1,
        des_cbc_md4                  = 2,
        des_cbc_md5                  = 3,
        des3_cbc_md5                 = 5,
        des3_cbc_sha1                = 7,
        dsaWithSHA1_CmsOID           = 9,
        md5WithRSAEncryption_CmsOID  = 10,
        sha1WithRSAEncryption_CmsOID = 11,
        rc2CBC_EnvOID                = 12,
        rsaEncryption_EnvOID         = 13,
        rsaES_OAEP_ENV_OID           = 14,
        des_ede3_cbc_Env_OID         = 15,
        des3_cbc_sha1_kd             = 16,
        aes128_cts_hmac_sha1_96      = 17,
        aes256_cts_hmac_sha1_96      = 18,
        aes128_cts_hmac_sha256_128   = 19,
        aes256_cts_hmac_sha384_192   = 20,
        rc4_hmac                     = 23,
        rc4_hmac_exp                 = 24,
        camellia128_cts_cmac         = 25,
        camellia256_cts_cmac         = 26,
        subkey_keymaterial           = 65,
    };
    const char *get_name() const {
        switch(encoded<T>::value()) {
        case reserved:                     return "reserved";
        case des_cbc_crc:                  return "des_cbc_crc";
        case des_cbc_md4:                  return "des_cbc_md4";
        case des_cbc_md5:                  return "des_cbc_md5";
        case des3_cbc_md5:                 return "des3_cbc_md5";
        case des3_cbc_sha1:                return "des3_cbc_sha1";
        case dsaWithSHA1_CmsOID:           return "dsaWithSHA1_CmsOID";
        case md5WithRSAEncryption_CmsOID:  return "md5WithRSAEncryption_CmsOID";
        case sha1WithRSAEncryption_CmsOID: return "sha1WithRSAEncryption_CmsOID";
        case rc2CBC_EnvOID:                return "rc2CBC_EnvOID";
        case rsaEncryption_EnvOID:         return "rsaEncryption_EnvOID";
        case rsaES_OAEP_ENV_OID:           return "rsaES_OAEP_ENV_OID";
        case des_ede3_cbc_Env_OID:         return "des_ede3_cbc_Env_OID";
        case des3_cbc_sha1_kd:             return "des3_cbc_sha1_kd";
        case aes128_cts_hmac_sha1_96:      return "aes128_cts_hmac_sha1_96";
        case aes256_cts_hmac_sha1_96:      return "aes256_cts_hmac_sha1_96";
        case aes128_cts_hmac_sha256_128:   return "aes128_cts_hmac_sha256_128";
        case aes256_cts_hmac_sha384_192:   return "aes256_cts_hmac_sha384_192";
        case rc4_hmac:                     return "rc4_hmac";
        case rc4_hmac_exp:                 return "rc4_hmac_exp";
        case camellia128_cts_cmac:         return "camellia128_cts_cmac";
        case camellia256_cts_cmac:         return "camellia256_cts_cmac";
        case subkey_keymaterial:           return "subkey_keymaterial";
        default:
            ;
        }
        return "unknown";
    }
};

template <typename T>
class checksum_type : public encoded<T> {
    static_assert(std::is_unsigned_v<T>, "T must be an unsigned integer");
public:
    void write_json(json_object &o) const {
        const char *name = get_name();
        if (name == nullptr) {
            o.print_key_unknown_code("checksum_type", encoded<T>::value());
        } else {
            o.print_key_string("checksum_type", name);
        }
    }
    enum code {
        CRC32                  = 1,
        rsa_md4                = 2,
        rsa_md4_des            = 3,
        des_mac                = 4,
        des_mac_k              = 5,
        rsa_md4_des_k          = 6,
        rsa_md5                = 7,
        rsa_md5_des            = 8,
        rsa_md5_des3           = 9,
        sha1                   = 10,
        hmac_sha1_des3_kd      = 12,
        hmac_sha1_des3         = 13,
        sha1_v2                = 14,
        hmac_sha1_96_aes128    = 15,
        hmac_sha1_96_aes256    = 16,
        cmac_camellia128       = 17,
        cmac_camellia256       = 18,
        hmac_sha256_128_aes128 = 19,
        hmac_sha384_192_aes256 = 20,
    };
    const char *get_name() const {
        switch(encoded<T>::value()) {
        case CRC32:                  return "CRC32";
        case rsa_md4:                return "rsa_md4";
        case rsa_md4_des:            return "rsa_md4_des";
        case des_mac:                return "des_mac";
        case des_mac_k:              return "des_mac_k";
        case rsa_md4_des_k:          return "rsa_md4_des_k";
        case rsa_md5:                return "rsa_md5";
        case rsa_md5_des:            return "rsa_md5_des";
        case rsa_md5_des3:           return "rsa_md5_des3";
        case sha1:                   return "sha1";
        case hmac_sha1_des3_kd:      return "hmac_sha1_des3_kd";
        case hmac_sha1_des3:         return "hmac_sha1_des3";
        case sha1_v2:                return "sha1";
        case hmac_sha1_96_aes128:    return "hmac_sha1_96_aes128";
        case hmac_sha1_96_aes256:    return "hmac_sha1_96_aes256";
        case cmac_camellia128:       return "cmac_camellia128";
        case cmac_camellia256:       return "cmac_camellia256";
        case hmac_sha256_128_aes128: return "hmac_sha256_128_aes128";
        case hmac_sha384_192_aes256: return "hmac_sha384_192_aes256";
        default:
            ;
        }
        return nullptr;
    }
};

template <typename T>
class pa_data_type : public encoded<T> {
    static_assert(std::is_unsigned_v<T>, "T must be an unsigned integer");
public:
    void write_json(json_object &o) const {
        const char *name = get_name();
        if (name == nullptr) {
            o.print_key_unknown_code("pa_data_type", encoded<T>::value());
        } else {
            o.print_key_string("pa_data_type", name);
        }
    }
    enum code {
        PA_TGS_REQ                 = 1,
        PA_ENC_TIMESTAMP           = 2,
        PA_PW_SALT                 = 3,
        reserved                   = 4,
        PA_ENC_UNIX_TIME           = 5,
        PA_SANDIA_SECUREID         = 6,
        PA_SESAME                  = 7,
        PA_OSF_DCE                 = 8,
        PA_CYBERSAFE_SECUREID      = 9,
        PA_AFS3_SALT               = 10,
        PA_ETYPE_INFO              = 11,
        PA_SAM_CHALLENGE           = 12,
        PA_SAM_RESPONSE            = 13,
        PA_PK_AS_REQ_OLD           = 14,
        PA_PK_AS_REP_OLD           = 15,
        PA_PK_AS_REQ               = 16,
        PA_PK_AS_REP               = 17,
        PA_PK_OCSP_RESPONSE        = 18,
        PA_ETYPE_INFO2             = 19,
        PA_USE_SPECIFIED_KVNO      = 20,
        // PA_SVR_REFERRAL_INFO    = 20,   // IANA assigns 20 twice ???
        PA_SAM_REDIRECT            = 21,
        PA_GET_FROM_TYPED_DATA     = 22,
        // TD_PADATA                  = 22,
        PA_SAM_ETYPE_INFO          = 23,
        PA_ALT_PRINC               = 24,
        PA_SERVER_REFERRAL         = 25,
        PA_SAM_CHALLENGE2          = 30,
        PA_SAM_RESPONSE2           = 31,
        PA_EXTRA_TGT               = 41,
        TD_PKINIT_CMS_CERTIFICATES = 101,
        TD_KRB_PRINCIPAL           = 102,
        TD_KRB_REALM               = 103,
        TD_TRUSTED_CERTIFIERS      = 104,
        TD_CERTIFICATE_INDEX       = 105,
        TD_APP_DEFINED_ERROR       = 106,
        TD_REQ_NONCE               = 107,
        TD_REQ_SEQ                 = 108,
        TD_DH_PARAMETERS           = 109,
        TD_CMS_DIGEST_ALGORITHMS   = 111,
        TD_CERT_DIGEST_ALGORITHMS  = 112,
        PA_PAC_REQUEST             = 128,
        PA_FOR_USER                = 129,
        PA_FOR_X509_USER           = 130,
        PA_FOR_CHECK_DUPS          = 131,
        PA_AS_CHECKSUM             = 132,
        PA_FX_COOKIE               = 133,
        PA_AUTHENTICATION_SET      = 134,
        PA_AUTH_SET_SELECTED       = 135,
        PA_FX_FAST                 = 136,
        PA_FX_ERROR                = 137,
        PA_ENCRYPTED_CHALLENGE     = 138,
        PA_OTP_CHALLENGE           = 141,
        PA_OTP_REQUEST             = 142,
        PA_OTP_CONFIRM             = 143,
        PA_OTP_PIN_CHANGE          = 144,
        PA_EPAK_AS_REQ             = 145,
        PA_EPAK_AS_REP             = 146,
        PA_PKINIT_KX               = 147,
        PA_PKU2U_NAME              = 148,
        PA_REQ_ENC_PA_REP          = 149,
        PA_AS_FRESHNESS            = 150,
        PA_SPAKE                   = 151,
        PA_REDHAT_IDP_OAUTH2       = 152,
        PA_REDHAT_PASSKEY          = 153,
        PA_SUPPORTED_ETYPES        = 165,
        PA_EXTENDED_ERROR          = 166,
    };
    const char *get_name() const {
        switch(encoded<T>::value()) {
        case PA_TGS_REQ:                 return "pa_tgs_req";
        case PA_ENC_TIMESTAMP:           return "pa_enc_timestamp";
        case PA_PW_SALT:                 return "pa_pw_salt";
        case reserved:                   return "reserved";
        case PA_ENC_UNIX_TIME:           return "pa_enc_unix_time";
        case PA_SANDIA_SECUREID:         return "pa_sandia_secureid";
        case PA_SESAME:                  return "pa_sesame";
        case PA_OSF_DCE:                 return "pa_osf_dce";
        case PA_CYBERSAFE_SECUREID:      return "pa_cybersafe_secureid";
        case PA_AFS3_SALT:               return "pa_afs3_salt";
        case PA_ETYPE_INFO:              return "pa_etype_info";
        case PA_SAM_CHALLENGE:           return "pa_sam_challenge";
        case PA_SAM_RESPONSE:            return "pa_sam_response";
        case PA_PK_AS_REQ_OLD:           return "pa_pk_as_req_old";
        case PA_PK_AS_REP_OLD:           return "pa_pk_as_rep_old";
        case PA_PK_AS_REQ:               return "pa_pk_as_req";
        case PA_PK_AS_REP:               return "pa_pk_as_rep";
        case PA_PK_OCSP_RESPONSE:        return "pa_pk_ocsp_response";
        case PA_ETYPE_INFO2:             return "pa_etype_info2";
        case PA_USE_SPECIFIED_KVNO:      return "pa_use_specified_kvno";
            // case PA_SVR_REFERRAL_INFO:       return "pa_svr_referral_info";
        case PA_SAM_REDIRECT:            return "pa_sam_redirect";
        case PA_GET_FROM_TYPED_DATA:     return "pa_get_from_typed_data";
            // case TD_PADATA:                  return "td_padata";
        case PA_SAM_ETYPE_INFO:          return "pa_sam_etype_info";
        case PA_ALT_PRINC:               return "pa_alt_princ";
        case PA_SERVER_REFERRAL:         return "pa_server_referral";
        case PA_SAM_CHALLENGE2:          return "pa_sam_challenge2";
        case PA_SAM_RESPONSE2:           return "pa_sam_response2";
        case PA_EXTRA_TGT:               return "pa_extra_tgt";
        case TD_PKINIT_CMS_CERTIFICATES: return "td_pkinit_cms_certificates";
        case TD_KRB_PRINCIPAL:           return "td_krb_principal";
        case TD_KRB_REALM:               return "td_krb_realm";
        case TD_TRUSTED_CERTIFIERS:      return "td_trusted_certifiers";
        case TD_CERTIFICATE_INDEX:       return "td_certificate_index";
        case TD_APP_DEFINED_ERROR:       return "td_app_defined_error";
        case TD_REQ_NONCE:               return "td_req_nonce";
        case TD_REQ_SEQ:                 return "td_req_seq";
        case TD_DH_PARAMETERS:           return "td_dh_parameters";
        case TD_CMS_DIGEST_ALGORITHMS:   return "td_cms_digest_algorithms";
        case TD_CERT_DIGEST_ALGORITHMS:  return "td_cert_digest_algorithms";
        case PA_PAC_REQUEST:             return "pa_pac_request";
        case PA_FOR_USER:                return "pa_for_user";
        case PA_FOR_X509_USER:           return "pa_for_x509_user";
        case PA_FOR_CHECK_DUPS:          return "pa_for_check_dups";
        case PA_AS_CHECKSUM:             return "pa_as_checksum";
        case PA_FX_COOKIE:               return "pa_fx_cookie";
        case PA_AUTHENTICATION_SET:      return "pa_authentication_set";
        case PA_AUTH_SET_SELECTED:       return "pa_auth_set_selected";
        case PA_FX_FAST:                 return "pa_fx_fast";
        case PA_FX_ERROR:                return "pa_fx_error";
        case PA_ENCRYPTED_CHALLENGE:     return "pa_encrypted_challenge";
        case PA_OTP_CHALLENGE:           return "pa_otp_challenge";
        case PA_OTP_REQUEST:             return "pa_otp_request";
        case PA_OTP_CONFIRM:             return "pa_otp_confirm";
        case PA_OTP_PIN_CHANGE:          return "pa_otp_pin_change";
        case PA_EPAK_AS_REQ:             return "pa_epak_as_req";
        case PA_EPAK_AS_REP:             return "pa_epak_as_rep";
        case PA_PKINIT_KX:               return "pa_pkinit_kx";
        case PA_PKU2U_NAME:              return "pa_pku2u_name";
        case PA_REQ_ENC_PA_REP:          return "pa_req_enc_pa_rep";
        case PA_AS_FRESHNESS:            return "pa_as_freshness";
        case PA_SPAKE:                   return "pa_spake";
        case PA_REDHAT_IDP_OAUTH2:       return "pa_redhat_idp_oauth2";
        case PA_REDHAT_PASSKEY:          return "pa_redhat_passkey";
        case PA_SUPPORTED_ETYPES:        return "pa_supported_etypes";
        case PA_EXTENDED_ERROR:          return "pa_extended_error";
        default:
            ;
        }
        return nullptr;
    }
};


#endif // KRB5_PARAMS_HPP
