// krb5_params.hpp
//
// this file was autogenerated at 2025-06-10T14:27:53Z
// you should edit the source file(s) instead of this one
//
// source files:
//     kerberos-parameters-1.csv
//     kerberos-parameters-2.csv
//     pre-authentication.csv
//

#ifndef KRB5_PARAMS_HPP
#define KRB5_PARAMS_HPP

template <typename T>
class encryption_type : public encoded<T> {
    static_assert(std::is_unsigned_v<T>, "T must be an unsigned integer");
public:
    void write_json(json_object &o) const {
        const char *name = get_name();
        if (name == nullptr) {
            o.print_key_unknown_code("encryption_type", encoded<T>::value());
        } else {
            o.print_key_string("encryption_type", name);
        }
    }
    enum code {
        reserved                     = 0,
        des_cbc_crc                  = 1,
        des_cbc_md4                  = 2,
        des_cbc_md5                  = 3,
        des3_cbc_md5                 = 5,
        des3_cbc_sha1                = 7,
        dsaWithSHA1_CmsOID           = 9,
        md5WithRSAEncryption_CmsOID  = 10,
        sha1WithRSAEncryption_CmsOID = 11,
        rc2CBC_EnvOID                = 12,
        rsaEncryption_EnvOID         = 13,
        rsaES_OAEP_ENV_OID           = 14,
        des_ede3_cbc_Env_OID         = 15,
        des3_cbc_sha1_kd             = 16,
        aes128_cts_hmac_sha1_96      = 17,
        aes256_cts_hmac_sha1_96      = 18,
        aes128_cts_hmac_sha256_128   = 19,
        aes256_cts_hmac_sha384_192   = 20,
        rc4_hmac                     = 23,
        rc4_hmac_exp                 = 24,
        camellia128_cts_cmac         = 25,
        camellia256_cts_cmac         = 26,
        subkey_keymaterial           = 65,
    };
    const char *get_name() const {
        switch(encoded<T>::value()) {
        case reserved:                     return "reserved";
        case des_cbc_crc:                  return "des_cbc_crc";
        case des_cbc_md4:                  return "des_cbc_md4";
        case des_cbc_md5:                  return "des_cbc_md5";
        case des3_cbc_md5:                 return "des3_cbc_md5";
        case des3_cbc_sha1:                return "des3_cbc_sha1";
        case dsaWithSHA1_CmsOID:           return "dsaWithSHA1_CmsOID";
        case md5WithRSAEncryption_CmsOID:  return "md5WithRSAEncryption_CmsOID";
        case sha1WithRSAEncryption_CmsOID: return "sha1WithRSAEncryption_CmsOID";
        case rc2CBC_EnvOID:                return "rc2CBC_EnvOID";
        case rsaEncryption_EnvOID:         return "rsaEncryption_EnvOID";
        case rsaES_OAEP_ENV_OID:           return "rsaES_OAEP_ENV_OID";
        case des_ede3_cbc_Env_OID:         return "des_ede3_cbc_Env_OID";
        case des3_cbc_sha1_kd:             return "des3_cbc_sha1_kd";
        case aes128_cts_hmac_sha1_96:      return "aes128_cts_hmac_sha1_96";
        case aes256_cts_hmac_sha1_96:      return "aes256_cts_hmac_sha1_96";
        case aes128_cts_hmac_sha256_128:   return "aes128_cts_hmac_sha256_128";
        case aes256_cts_hmac_sha384_192:   return "aes256_cts_hmac_sha384_192";
        case rc4_hmac:                     return "rc4_hmac";
        case rc4_hmac_exp:                 return "rc4_hmac_exp";
        case camellia128_cts_cmac:         return "camellia128_cts_cmac";
        case camellia256_cts_cmac:         return "camellia256_cts_cmac";
        case subkey_keymaterial:           return "subkey_keymaterial";
        default:
            ;
        }
        return nullptr;
    }
};

template <typename T>
class checksum_type : public encoded<T> {
    static_assert(std::is_unsigned_v<T>, "T must be an unsigned integer");
public:
    void write_json(json_object &o) const {
        const char *name = get_name();
        if (name == nullptr) {
            o.print_key_unknown_code("checksum_type", encoded<T>::value());
        } else {
            o.print_key_string("checksum_type", name);
        }
    }
    enum code {
        CRC32                  = 1,
        rsa_md4                = 2,
        rsa_md4_des            = 3,
        des_mac                = 4,
        des_mac_k              = 5,
        rsa_md4_des_k          = 6,
        rsa_md5                = 7,
        rsa_md5_des            = 8,
        rsa_md5_des3           = 9,
        sha1                   = 10,
        hmac_sha1_des3_kd      = 12,
        hmac_sha1_des3         = 13,
        sha1_v2                = 14,
        hmac_sha1_96_aes128    = 15,
        hmac_sha1_96_aes256    = 16,
        cmac_camellia128       = 17,
        cmac_camellia256       = 18,
        hmac_sha256_128_aes128 = 19,
        hmac_sha384_192_aes256 = 20,
    };
    const char *get_name() const {
        switch(encoded<T>::value()) {
        case CRC32:                  return "CRC32";
        case rsa_md4:                return "rsa_md4";
        case rsa_md4_des:            return "rsa_md4_des";
        case des_mac:                return "des_mac";
        case des_mac_k:              return "des_mac_k";
        case rsa_md4_des_k:          return "rsa_md4_des_k";
        case rsa_md5:                return "rsa_md5";
        case rsa_md5_des:            return "rsa_md5_des";
        case rsa_md5_des3:           return "rsa_md5_des3";
        case sha1:                   return "sha1";
        case hmac_sha1_des3_kd:      return "hmac_sha1_des3_kd";
        case hmac_sha1_des3:         return "hmac_sha1_des3";
        case sha1:                   return "sha1";
        case hmac_sha1_96_aes128:    return "hmac_sha1_96_aes128";
        case hmac_sha1_96_aes256:    return "hmac_sha1_96_aes256";
        case cmac_camellia128:       return "cmac_camellia128";
        case cmac_camellia256:       return "cmac_camellia256";
        case hmac_sha256_128_aes128: return "hmac_sha256_128_aes128";
        case hmac_sha384_192_aes256: return "hmac_sha384_192_aes256";
        default:
            ;
        }
        return nullptr;
    }
};

template <typename T>
class pa_data_type : public encoded<T> {
    static_assert(std::is_unsigned_v<T>, "T must be an unsigned integer");
public:
    void write_json(json_object &o) const {
        const char *name = get_name();
        if (name == nullptr) {
            o.print_key_unknown_code("pa_data_type", encoded<T>::value());
        } else {
            o.print_key_string("pa_data_type", name);
        }
    }
    enum code {
        PA_TGS_REQ                 = 1,
        PA_ENC_TIMESTAMP           = 2,
        PA_PW_SALT                 = 3,
        reserved                   = 4,
        PA_ENC_UNIX_TIME           = 5,
        PA_SANDIA_SECUREID         = 6,
        PA_SESAME                  = 7,
        PA_OSF_DCE                 = 8,
        PA_CYBERSAFE_SECUREID      = 9,
        PA_AFS3_SALT               = 10,
        PA_ETYPE_INFO              = 11,
        PA_SAM_CHALLENGE           = 12,
        PA_SAM_RESPONSE            = 13,
        PA_PK_AS_REQ_OLD           = 14,
        PA_PK_AS_REP_OLD           = 15,
        PA_PK_AS_REQ               = 16,
        PA_PK_AS_REP               = 17,
        PA_PK_OCSP_RESPONSE        = 18,
        PA_ETYPE_INFO2             = 19,
        PA_USE_SPECIFIED_KVNO      = 20,
        // PA_SVR_REFERRAL_INFO    = 20,   // IANA assigns 20 twice ???
        PA_SAM_REDIRECT            = 21,
        PA_GET_FROM_TYPED_DATA     = 22,
        // TD_PADATA                  = 22,
        PA_SAM_ETYPE_INFO          = 23,
        PA_ALT_PRINC               = 24,
        PA_SERVER_REFERRAL         = 25,
        PA_SAM_CHALLENGE2          = 30,
        PA_SAM_RESPONSE2           = 31,
        PA_EXTRA_TGT               = 41,
        TD_PKINIT_CMS_CERTIFICATES = 101,
        TD_KRB_PRINCIPAL           = 102,
        TD_KRB_REALM               = 103,
        TD_TRUSTED_CERTIFIERS      = 104,
        TD_CERTIFICATE_INDEX       = 105,
        TD_APP_DEFINED_ERROR       = 106,
        TD_REQ_NONCE               = 107,
        TD_REQ_SEQ                 = 108,
        TD_DH_PARAMETERS           = 109,
        TD_CMS_DIGEST_ALGORITHMS   = 111,
        TD_CERT_DIGEST_ALGORITHMS  = 112,
        PA_PAC_REQUEST             = 128,
        PA_FOR_USER                = 129,
        PA_FOR_X509_USER           = 130,
        PA_FOR_CHECK_DUPS          = 131,
        PA_AS_CHECKSUM             = 132,
        PA_FX_COOKIE               = 133,
        PA_AUTHENTICATION_SET      = 134,
        PA_AUTH_SET_SELECTED       = 135,
        PA_FX_FAST                 = 136,
        PA_FX_ERROR                = 137,
        PA_ENCRYPTED_CHALLENGE     = 138,
        PA_OTP_CHALLENGE           = 141,
        PA_OTP_REQUEST             = 142,
        PA_OTP_CONFIRM             = 143,
        PA_OTP_PIN_CHANGE          = 144,
        PA_EPAK_AS_REQ             = 145,
        PA_EPAK_AS_REP             = 146,
        PA_PKINIT_KX               = 147,
        PA_PKU2U_NAME              = 148,
        PA_REQ_ENC_PA_REP          = 149,
        PA_AS_FRESHNESS            = 150,
        PA_SPAKE                   = 151,
        PA_REDHAT_IDP_OAUTH2       = 152,
        PA_REDHAT_PASSKEY          = 153,
        PA_SUPPORTED_ETYPES        = 165,
        PA_EXTENDED_ERROR          = 166,
    };
    const char *get_name() const {
        switch(encoded<T>::value()) {
        case PA_TGS_REQ:                 return "PA_TGS_REQ";
        case PA_ENC_TIMESTAMP:           return "PA_ENC_TIMESTAMP";
        case PA_PW_SALT:                 return "PA_PW_SALT";
        case reserved:                   return "reserved";
        case PA_ENC_UNIX_TIME:           return "PA_ENC_UNIX_TIME";
        case PA_SANDIA_SECUREID:         return "PA_SANDIA_SECUREID";
        case PA_SESAME:                  return "PA_SESAME";
        case PA_OSF_DCE:                 return "PA_OSF_DCE";
        case PA_CYBERSAFE_SECUREID:      return "PA_CYBERSAFE_SECUREID";
        case PA_AFS3_SALT:               return "PA_AFS3_SALT";
        case PA_ETYPE_INFO:              return "PA_ETYPE_INFO";
        case PA_SAM_CHALLENGE:           return "PA_SAM_CHALLENGE";
        case PA_SAM_RESPONSE:            return "PA_SAM_RESPONSE";
        case PA_PK_AS_REQ_OLD:           return "PA_PK_AS_REQ_OLD";
        case PA_PK_AS_REP_OLD:           return "PA_PK_AS_REP_OLD";
        case PA_PK_AS_REQ:               return "PA_PK_AS_REQ";
        case PA_PK_AS_REP:               return "PA_PK_AS_REP";
        case PA_PK_OCSP_RESPONSE:        return "PA_PK_OCSP_RESPONSE";
        case PA_ETYPE_INFO2:             return "PA_ETYPE_INFO2";
        case PA_USE_SPECIFIED_KVNO:      return "PA_USE_SPECIFIED_KVNO";
            // case PA_SVR_REFERRAL_INFO:       return "PA_SVR_REFERRAL_INFO";
        case PA_SAM_REDIRECT:            return "PA_SAM_REDIRECT";
        case PA_GET_FROM_TYPED_DATA:     return "PA_GET_FROM_TYPED_DATA";
            // case TD_PADATA:                  return "TD_PADATA";
        case PA_SAM_ETYPE_INFO:          return "PA_SAM_ETYPE_INFO";
        case PA_ALT_PRINC:               return "PA_ALT_PRINC";
        case PA_SERVER_REFERRAL:         return "PA_SERVER_REFERRAL";
        case PA_SAM_CHALLENGE2:          return "PA_SAM_CHALLENGE2";
        case PA_SAM_RESPONSE2:           return "PA_SAM_RESPONSE2";
        case PA_EXTRA_TGT:               return "PA_EXTRA_TGT";
        case TD_PKINIT_CMS_CERTIFICATES: return "TD_PKINIT_CMS_CERTIFICATES";
        case TD_KRB_PRINCIPAL:           return "TD_KRB_PRINCIPAL";
        case TD_KRB_REALM:               return "TD_KRB_REALM";
        case TD_TRUSTED_CERTIFIERS:      return "TD_TRUSTED_CERTIFIERS";
        case TD_CERTIFICATE_INDEX:       return "TD_CERTIFICATE_INDEX";
        case TD_APP_DEFINED_ERROR:       return "TD_APP_DEFINED_ERROR";
        case TD_REQ_NONCE:               return "TD_REQ_NONCE";
        case TD_REQ_SEQ:                 return "TD_REQ_SEQ";
        case TD_DH_PARAMETERS:           return "TD_DH_PARAMETERS";
        case TD_CMS_DIGEST_ALGORITHMS:   return "TD_CMS_DIGEST_ALGORITHMS";
        case TD_CERT_DIGEST_ALGORITHMS:  return "TD_CERT_DIGEST_ALGORITHMS";
        case PA_PAC_REQUEST:             return "PA_PAC_REQUEST";
        case PA_FOR_USER:                return "PA_FOR_USER";
        case PA_FOR_X509_USER:           return "PA_FOR_X509_USER";
        case PA_FOR_CHECK_DUPS:          return "PA_FOR_CHECK_DUPS";
        case PA_AS_CHECKSUM:             return "PA_AS_CHECKSUM";
        case PA_FX_COOKIE:               return "PA_FX_COOKIE";
        case PA_AUTHENTICATION_SET:      return "PA_AUTHENTICATION_SET";
        case PA_AUTH_SET_SELECTED:       return "PA_AUTH_SET_SELECTED";
        case PA_FX_FAST:                 return "PA_FX_FAST";
        case PA_FX_ERROR:                return "PA_FX_ERROR";
        case PA_ENCRYPTED_CHALLENGE:     return "PA_ENCRYPTED_CHALLENGE";
        case PA_OTP_CHALLENGE:           return "PA_OTP_CHALLENGE";
        case PA_OTP_REQUEST:             return "PA_OTP_REQUEST";
        case PA_OTP_CONFIRM:             return "PA_OTP_CONFIRM";
        case PA_OTP_PIN_CHANGE:          return "PA_OTP_PIN_CHANGE";
        case PA_EPAK_AS_REQ:             return "PA_EPAK_AS_REQ";
        case PA_EPAK_AS_REP:             return "PA_EPAK_AS_REP";
        case PA_PKINIT_KX:               return "PA_PKINIT_KX";
        case PA_PKU2U_NAME:              return "PA_PKU2U_NAME";
        case PA_REQ_ENC_PA_REP:          return "PA_REQ_ENC_PA_REP";
        case PA_AS_FRESHNESS:            return "PA_AS_FRESHNESS";
        case PA_SPAKE:                   return "PA_SPAKE";
        case PA_REDHAT_IDP_OAUTH2:       return "PA_REDHAT_IDP_OAUTH2";
        case PA_REDHAT_PASSKEY:          return "PA_REDHAT_PASSKEY";
        case PA_SUPPORTED_ETYPES:        return "PA_SUPPORTED_ETYPES";
        case PA_EXTENDED_ERROR:          return "PA_EXTENDED_ERROR";
        default:
            ;
        }
        return nullptr;
    }
};


#endif // KRB5_PARAMS_HPP

