
-- Cisco_ACT2_SUDI is defined in "ACT2 SUDI CA Certification Practice
-- Statement”, available online at
-- https://www.cisco.com/security/pki/policies/ACT2_SUDI_CA_CPS_v2.0.pdf,
-- as is defined as:
--
--    The Subject Alternate Name (or subjectAltName) field is an
--    X.509v3 extension which consists of a single “GeneralName” of
--    “OtherName [0]” type with a type-id OID of 1.3.6.1.4.1.9.21.2.3
--    and a value of the PrintableString “ChipID=<chipSN>”, where
--    “chipSN” is the BASE64-encoded ACT2 Chip Serial Number. This
--    ChipSN is validated as unique across all certificates issued by
--    the ACT2 SubCAs, and the ChipSN must match a pre-registered ACT2
--    chip serial number in the ACT2 SubCAs’ database prior to
--    issuance.


Cisco_ACT2_SUDI  OBJECT IDENTIFIER ::= { 1 3 6 1 4 1 9 21 2 3 }